spring.docker.compose.enabled=true

spring.datasource.url=jdbc:postgresql://localhost:5432/springai
spring.datasource.username=springai
spring.datasource.password=springai

spring.ai.vectorstore.pgvector.initialize-schema=true

# Vektordimension MUSS zur EmbeddingModel-Ausgabe passen.
spring.ai.vectorstore.pgvector.dimensions=256
spring.ai.vectorstore.pgvector.index-type=HNSW
spring.ai.vectorstore.pgvector.distance-type=COSINE_DISTANCE
