-- ============================================================================
-- Schema fuer den eGK-/Gesundheits-/PKI-Testdaten-Generator
-- ----------------------------------------------------------------------------
-- Eine kleine, aber kohaerente "Telematik-Welt": Krankenkassen, Versicherte mit
-- elektronischer Gesundheitskarte (eGK), Leistungserbringer (Aerzte/Apotheken),
-- Diagnosen (ICD-10) sowie die zugehoerigen digitalen Zertifikate (HBA/SMC-B/
-- eGK) inkl. ausstellender CA.
--
-- WICHTIG: Alle Daten sind rein SYNTHETISCH (DSGVO-sicher). Nummern wie KVNR,
-- IK, ICCSN tragen zwar korrekte Pruefziffern/Formate, gehoeren aber zu keiner
-- realen Person/Institution. X.509-Felder sind Metadaten (keine echte Krypto).
--
-- Wird wie schema.sql per spring.sql.init ausgefuehrt und ist bewusst ANSI-nah
-- gehalten, sodass es sowohl auf PostgreSQL (App) als auch auf H2 (Tests) laeuft.
-- 'IF NOT EXISTS' macht das Skript idempotent.
-- ============================================================================

-- Krankenkassen (GKV/PKV) ----------------------------------------------------
CREATE TABLE IF NOT EXISTS krankenkassen (
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ik    VARCHAR(9)   NOT NULL,            -- Institutionskennzeichen (9-stellig, Luhn)
    name  VARCHAR(120) NOT NULL,
    typ   VARCHAR(8)   NOT NULL             -- GKV / PKV
);

-- Ausstellende Zertifizierungsstellen (Trust-Chain der Telematik) -------------
CREATE TABLE IF NOT EXISTS ca_zertifikate (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(120) NOT NULL,     -- z.B. GEM.HBA-CA24 TEST-ONLY
    subject_dn   VARCHAR(255) NOT NULL,
    seriennummer VARCHAR(40)  NOT NULL,
    not_before   DATE NOT NULL,
    not_after    DATE NOT NULL
);

-- Leistungserbringer (Aerzte/Apotheken/Kliniken) -----------------------------
CREATE TABLE IF NOT EXISTS leistungserbringer (
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    typ   VARCHAR(16)  NOT NULL,            -- ARZT / APOTHEKE / KRANKENHAUS
    name  VARCHAR(120) NOT NULL,
    lanr  VARCHAR(9),                       -- Lebenslange Arztnummer (nur ARZT)
    bsnr  VARCHAR(9),                       -- Betriebsstaettennummer
    plz   VARCHAR(5)   NOT NULL,
    ort   VARCHAR(80)  NOT NULL
);

-- Versicherte (Patienten) ----------------------------------------------------
CREATE TABLE IF NOT EXISTS versicherte (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kvnr            VARCHAR(10) NOT NULL,    -- Krankenversichertennummer (korrekte Pruefziffer)
    vorname         VARCHAR(60) NOT NULL,
    nachname        VARCHAR(60) NOT NULL,
    geburtsdatum    DATE        NOT NULL,
    geschlecht      VARCHAR(1)  NOT NULL,    -- M/W/D
    plz             VARCHAR(5)  NOT NULL,
    ort             VARCHAR(80) NOT NULL,
    strasse         VARCHAR(120) NOT NULL,
    krankenkasse_id BIGINT      NOT NULL REFERENCES krankenkassen(id)
);

-- Elektronische Gesundheitskarten --------------------------------------------
CREATE TABLE IF NOT EXISTS egk_karten (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    iccsn          VARCHAR(20) NOT NULL,     -- ICC Serial Number (Chipnummer)
    can            VARCHAR(6)  NOT NULL,     -- Card Access Number
    versicherte_id BIGINT      NOT NULL REFERENCES versicherte(id),
    gueltig_von    DATE        NOT NULL,
    gueltig_bis    DATE        NOT NULL,
    status         VARCHAR(12) NOT NULL      -- AKTIV / GESPERRT / ERSETZT
);

-- Diagnosen (ICD-10) ---------------------------------------------------------
CREATE TABLE IF NOT EXISTS diagnosen (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    versicherte_id        BIGINT       NOT NULL REFERENCES versicherte(id),
    leistungserbringer_id BIGINT       NOT NULL REFERENCES leistungserbringer(id),
    icd10                 VARCHAR(8)   NOT NULL,
    diagnose_text         VARCHAR(200) NOT NULL,
    diagnose_datum        DATE         NOT NULL
);

-- Digitale Zertifikate (HBA/SMC-B/eGK) ---------------------------------------
CREATE TABLE IF NOT EXISTS zertifikate (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    typ              VARCHAR(12)  NOT NULL,  -- HBA / SMC_B / EGK_AUT / EGK_ENC
    seriennummer     VARCHAR(40)  NOT NULL,  -- hexadezimal
    subject_dn       VARCHAR(255) NOT NULL,
    ca_id            BIGINT       NOT NULL REFERENCES ca_zertifikate(id),
    inhaber_typ      VARCHAR(20)  NOT NULL,  -- LEISTUNGSERBRINGER / VERSICHERTER (polymorph, daher kein FK)
    inhaber_id       BIGINT       NOT NULL,
    not_before       DATE         NOT NULL,
    not_after        DATE         NOT NULL,
    status           VARCHAR(8)   NOT NULL,  -- VALID / REVOKED / EXPIRED
    revocation_datum DATE                    -- gesetzt nur bei status=REVOKED
);
