-- ============================================================================
-- Schema fuer Feature E: Persistenz der Ticket-Analyse (Structured Output)
-- ----------------------------------------------------------------------------
-- Wird per spring.sql.init.mode=always bei jedem Start ausgefuehrt. Die SQL ist
-- bewusst ANSI-nah gehalten, sodass sie sowohl auf PostgreSQL (App) als auch auf
-- H2 (Tests) laeuft. 'IF NOT EXISTS' macht das Skript idempotent.
-- ============================================================================
CREATE TABLE IF NOT EXISTS tickets (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category      VARCHAR(32)  NOT NULL,
    priority      VARCHAR(16)  NOT NULL,
    sentiment     VARCHAR(16)  NOT NULL,
    summary       VARCHAR(2000),
    original_text VARCHAR(8000),
    created_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- ============================================================================
-- Feature 18: docs_rag - Status-Tracking der Live-Ingestion von gemspec-PDFs
-- ----------------------------------------------------------------------------
-- Eine Zeile = ein zu verarbeitendes Spec-PDF aus dem gemspec-Katalog
-- (sitemap.xml). status durchlaeuft 'incoming' -> 'processed' | 'error'.
-- Die 4 UI-Zaehler sind COUNT(*) bzw. GROUP BY status. ANSI-nah (H2 + Postgres).
-- ============================================================================
CREATE TABLE IF NOT EXISTS docs_rag (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    spec          VARCHAR(256)  NOT NULL,
    version       VARCHAR(64)   NOT NULL,
    category      VARCHAR(64)   NOT NULL,
    pdf_url       VARCHAR(1024) NOT NULL,
    status        VARCHAR(16)   NOT NULL DEFAULT 'incoming',
    chunks        INTEGER,
    error_message VARCHAR(2000),
    created_at    TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    processed_at  TIMESTAMP,
    CONSTRAINT uq_docs_rag_spec_version UNIQUE (spec, version)
);
