-- ============================================================================
-- Schema fuer Feature 21: Persistenz der KI-gestuetzten Exception-Triage
-- ----------------------------------------------------------------------------
-- Eine Zeile = eine abgeschlossene Analyse einer Stoerung. Wird per
-- spring.sql.init.mode=always bei jedem Start ausgefuehrt. ANSI-nah, laeuft auf
-- PostgreSQL (App) und H2 (Tests). 'IF NOT EXISTS' macht das Skript idempotent.
-- ============================================================================
CREATE TABLE IF NOT EXISTS exception_triage (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fingerprint      VARCHAR(512) NOT NULL,
    error_id         VARCHAR(64)  NOT NULL,
    exception_type   VARCHAR(256) NOT NULL,
    path             VARCHAR(512),
    category         VARCHAR(32)  NOT NULL,
    severity         VARCHAR(16)  NOT NULL,
    retriable        BOOLEAN      NOT NULL,
    root_cause       VARCHAR(2000),
    suggested_action VARCHAR(2000),
    user_message     VARCHAR(2000),
    created_at       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);
