-- ============================================================================
-- Schema fuer Feature E: Persistenz der Ticket-Analyse (Structured Output)
-- ----------------------------------------------------------------------------
-- Wird per spring.sql.init.mode=always bei jedem Start ausgefuehrt. Die SQL ist
-- bewusst ANSI-nah gehalten, sodass sie sowohl auf PostgreSQL (App) als auch auf
-- H2 (Tests) laeuft. 'IF NOT EXISTS' macht das Skript idempotent.
-- ============================================================================
CREATE TABLE IF NOT EXISTS tickets (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category      VARCHAR(32)  NOT NULL,
    priority      VARCHAR(16)  NOT NULL,
    sentiment     VARCHAR(16)  NOT NULL,
    summary       VARCHAR(2000),
    original_text VARCHAR(8000),
    created_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);
