-- ============================================================================
-- Schema fuer Feature 16: tool_calling_expert - persistierte Downloads (H2)
-- ----------------------------------------------------------------------------
-- Eine Zeile = eine erfolgreich heruntergeladene Datei (aktuell: Open-Access-PDFs
-- aus OpenAlex). Die rohen Bytes liegen bewusst in der DB - bei kleinen PDFs
-- unkritisch und gut, um das "Tool laedt -> App stellt bereit"-Muster vollstaendig
-- in einer Tabelle zu zeigen. Die eigentliche Auslieferung der Bytes erledigt ein
-- normaler REST-Endpoint (/api/downloads/{id}/file), nicht das LLM.
--
-- WICHTIG: Fuer den Binaer-Typ gibt es kein gemeinsames Schluesselwort von H2 und
-- PostgreSQL. Diese Datei ist die H2-/Default-/Test-Variante (BLOB); das Profil
-- 'postgres' laedt stattdessen schema-downloads-postgres.sql (bytea). 'IF NOT
-- EXISTS' macht das Skript idempotent.
-- ============================================================================
CREATE TABLE IF NOT EXISTS downloads (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_type  VARCHAR(10)  NOT NULL,           -- aktuell immer 'PAPER'
    title        VARCHAR(500) NOT NULL,
    source_ref   VARCHAR(500) NOT NULL,           -- z.B. 'openalex:W2741809807'
    content_type VARCHAR(100) NOT NULL,           -- application/pdf
    size_bytes   BIGINT       NOT NULL,
    data         BYTEA        NOT NULL,           -- die rohen Datei-Bytes (H2: BLOB)
    created_at   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);
